agent:
  batch_size: 4
  device: cuda
  discount: 0.5
  double_q_learning: false
  epsilon_decay: 100000
  epsilon_end: 0.05
  epsilon_start: 0.9
  goal: true
  learning_rate: 0.0001
  param: 0.0
  push_target_prob: 0.5
  replay_buffer_size: 1000000
  tau: 0.999
  update_target_net: 500
env:
  camera:
    intrinsics:
      cx: 320
      cy: 240
      fx: 463
      fy: 463
      height: 480
      width: 640
    pos:
    - 0.0
    - 0.0
    - 0.6
    target_pos:
    - 0.0
    - 0.0
    - 0.0
    up_vector:
    - 0.0
    - 1.0
    - 0.0
  render: true
  scene_generation:
    all_equal_height_prob: 1.0
    hug:
      probability: 1
      radius: 0.2
    nr_of_obstacles:
    - 5
    - 5
    object_type: boxes
    obstacle:
      max_bounding_box:
      - 0.03
      - 0.03
      - 0.03
      min_bounding_box:
      - 0.03
      - 0.03
      - 0.03
      probability_box: 1.0
      pushable_threshold_coeff: -0.5
    target:
      enforce_convex_hull: 15
      max_bounding_box:
      - 0.03
      - 0.03
      - 0.03
      min_bounding_box:
      - 0.03
      - 0.03
      - 0.03
      probability_box: 1.0
      randomize_pos: true
  workspace:
    pos:
    - -0.614
    - 0
    - 0
    quat:
      w: 0.7071232
      x: 0.0
      y: 0.0
      z: 0.707904
    size:
    - 0.5
    - 0.5
    walls: false
mdp:
  push:
    distance:
    - 0.02
    - 0.1
    obstacle_avoid: true
    predict_collision: true
  singulation_distance: 0.03
